# List options: ./flags.sh -LH
# Webcam support: sudo apt install libv4l-dev libv4l2rds0t64  -DCHANNEL_RDPECAM_CLIENT=ON -DCHANNEL_RDPECAM=ON
set -x
cmake -GNinja -B build -S . "$@" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/.local  \
  -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=OFF \
  -DWITH_X11=ON -DWITH_FFMPEG=ON \
  -DWITH_SWSCALE=ON -DWITH_DSP_FFMPEG=ON -DWITH_OPENH264=ON -DWITH_SERVER=OFF \
  -DWITH_SHADOW=OFF -DWITH_PROXY=OFF -DWITH_SAMPLE=OFF \
  -DWITH_PLATFORM_SERVER=OFF -DWITH_PULSEAUDIO=ON -DWITH_PULSE=ON -DWITH_CUPS=ON \
  -DWITH_FUSE=ON -DWITH_WEBVIEW=OFF -DUSE_UNWIND=OFF -DWITH_CLIENT_SDL=OFF \
  -DWITH_VERBOSE_WINPR_ASSERT=OFF -DWITH_CLIENT_WAYLAND=OFF -DWITH_WAYLAND=OFF \
  -DWITH_DEBUG_UTILS_CMDLINE_DUMP=ON -DWITH_DSP_EXPERIMENTAL=ON \
  -DCHANNEL_RDPECAM_CLIENT=ON -DCHANNEL_RDPECAM=ON \
  -DWITH_PKCS11=ON -DWITH_PCSC=ON -DWITH_PROXY_EMULATE_SMARTCARD=ON -DWITH_SMARTCARD_PCSC=ON

